#!/bin/bash
#
# Cargo - an object that passes through a Docker container
#
# Author: Kyle Manna <kyle@kylemanna.com>
#

IMG=$1
SRC=$2

#
# When invoked from the host (i.e. transmitter)
#
if [ -z "$IMG" -o -z "$SRC" ]; then
    echo "Invalid arguments"
    echo
    echo "usage: $0 DOCKER_IMAGE CARGO_SRC_DIRECTORY"
    echo
    exit 1
fi

docker run -v $(readlink -f $SRC):/cargo --rm -it $IMG /cargo/run.sh
